config/routes.rb
Rails.application.routes.draw do

  resources :patients do
    resources :appointments
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :patient, optional: true
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.where("patient_id = ?", patient_params[:patient_id])
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    patient = Patient.find(patient_params[:patient_id])
    @appointment =  patient.appointments.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create



    patient = Patient.find(params[:patient_id])

    byebug

    @appointment =  patient.appointments.new(appointment_params)
    # appointment_params
    # byebug

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to patient_appointments_path, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to put_patient_appointment_path, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to patient_appointments_url, notice: 'Appointment was successfully destroyed.' }
      
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:date, :time, :clinic, :address, :patient_id)
    end
    def patient_params
      params.permit(:patient_id)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:name, :ssn, :phone_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/patient_appointment_helper.rb
module PatientAppointmentHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/_form.html.erb
<%= form_with(url: patient_appointments_path ,model: appointment , local: true) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date, id: :appointment_date %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.text_field :time, id: :appointment_time %>
  </div>

  <div class="field">
    <%= form.label :clinic %>
    <%= form.text_field :clinic, id: :appointment_clinic %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :appointment_address %>
  </div>

  <div class="field">
    <%= form.label :patient_id %>
    <%= form.number_field :patient_id, id: :appointment_patient_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', patient_appointment_path(@apponitment.patient, @appointment) %> |
<%= link_to 'Back', patient_appointments_path(@appointment.patient) %>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Time</th>
      <th>Clinic</th>
      <th>Address</th>
      <th>Patient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.date %></td>
        <td><%= appointment.time %></td>
        <td><%= appointment.clinic %></td>
        <td><%= appointment.address %></td>
        <td><%= appointment.patient_id %></td>
        <td><%= link_to 'Show', patient_appointment_path(appointment.patient.id, appointment) %></td>
        <td><%= link_to 'Edit', edit_patient_appointment_path(appointment.patient.id, appointment) %></td>
        <td><%= link_to 'Destroy', patient_appointment_path(appointment.patient.id, appointment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_patient_appointment_path %>

<%= link_to 'back', patient_path(@appointments.first.patient) %>
<%= render 'partials/footer', patient: @appointments.first.patient %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', patient_appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @appointment.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @appointment.time %>
</p>

<p>
  <strong>Clinic:</strong>
  <%= @appointment.clinic %>
</p>

<p>
  <strong>Address:</strong>
  <%= @appointment.address %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @appointment.patient_id %>
</p>

<%= link_to 'Edit', edit_patient_appointment_path(@appointment) %> |
<%= link_to 'Back', patient_appointments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clinic</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/_footer.erb
<h1><%=patient.name%></h1>

app/views/patients/_form.html.erb
<%= form_with(model: patient, local: true) do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :patient_name %>
  </div>

  <div class="field">
    <%= form.label :ssn %>
    <%= form.text_field :ssn, id: :patient_ssn %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number, id: :patient_phone_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/patients/add_appointment.html.erb
<h1>Add Appointment</h1>

<%= render 'form', appointment: @patient %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Patients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ssn</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.name %></td>
        <td><%= patient.ssn %></td>
        <td><%= patient.phone_number %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @patient.name %>
</p>

<p>
  <strong>Ssn:</strong>
  <%= @patient.ssn %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @patient.phone_number %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'appointments', patient_appointments_path(@patient) %> |
<%= link_to 'Back', patients_path %>
<%= link_to '<button type="button">Add appointment</button>'.html_safe, new_patient_appointment_path(@patient) %>
<%= render 'partials/footer', patient: @patient %>